package uga.edu.cs.myapplication;

import java.util.HashMap;
import java.util.Map;


/*
    Every product contains a product key, name and price. The product key
    is generated by Firebase every time an element is added and then assigned
    to the specific product (look inside the "addProduct" method of the
    databaseManager class to see how it works).
 */
public class Product {



    private String productKey = "";
    private String name;

    private int price;

    public Product() {

    }

    public Product(String name, int price) {
        this.name = name;
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public String getProductKey() {
        return productKey;
    }

    public void setProductKey(String productKey) {
        this.productKey = productKey;
    }

    public Map<String, Object> toMap() {
        HashMap<String, Object> result = new HashMap<>();
        result.put("name", this.getName());
        result.put("price", this.getPrice());
        return result;
    }

    @Override
    public String toString() {
        return "Product{" +
                "name='" + name + '\'' +
                ", price=" + price +
                '}';
    }


}
